version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:80"
